Update sync.yml

diff --git a/.github/workflows/sync.yml b/.github/workflows/sync.yml
--- a/.github/workflows/sync.yml
+++ b/.github/workflows/sync.yml
@@ -1,20 +1,40 @@
-name: Sync Fork Upstream
+name: Upstream Sync
+
+permissions:
+  contents: write
 
 on:
   schedule:
-    - cron: '0 8 * * *' # every day 8am
-  workflow_dispatch: # on button click
+    - cron: "0 * * * *" # every hour
+  workflow_dispatch:
 
 jobs:
-  sync:
-
+  sync_latest_from_upstream:
+    name: Sync latest commits from upstream repo
     runs-on: ubuntu-latest
+    if: ${{ github.event.repository.fork }}
 
     steps:
-      - uses: AbdulmelikKalkan/sync-fork-upstream@v1.3
-        env:
-          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
+      # Step 1: run a standard checkout action
+      - name: Checkout target repo
+        uses: actions/checkout@v3
+
+      # Step 2: run the sync action
+      - name: Sync upstream changes
+        id: sync
+        uses: aormsby/Fork-Sync-With-Upstream-action@v3.4
         with:
-          owner: Mydong
-          repo: alist-encrypt
-          branch: main
+          upstream_sync_repo: traceless/alist-encrypt  #修改为要同步的上游仓库地址
+          upstream_sync_branch: main
+          target_sync_branch: main
+          target_repo_token: ${{ secrets.ACCESS_TOKEN }} # automatically generated, no need to set
+
+          # Set test_mode true to run tests instead of the true action!!
+          test_mode: false
+
+      - name: Sync check
+        if: failure()
+        run: |
+          echo "::error::由于权限不足，导致同步失败（这是预期的行为），请前往仓库首页手动执行[Sync fork]。"
+          echo "::error::Due to insufficient permissions, synchronization failed (as expected). Please go to the repository homepage and manually perform [Sync fork]."
+          exit 1
